"""
Django settings for djFolio project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# django parler settings
PARLER_LANGUAGES = {
    None : (
        {'code' : 'fr'},
        {'code' : 'en'}
    ),
    'default' : {
        'fallback' : 'fr',
        'hide_untranslated' : False,
    }
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == 'True'

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS").split(',')

# Application definition

INSTALLED_APPS = [
    'jazzmin', # admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # my apps
    'folio.apps.FolioConfig',
    # pip apps
    'parler',
    'rosetta',
    'storages',
    'debug_toolbar',
]
JAZZMIN_SETTINGS = {
    "site_title": "JEAN DJANTA PortFolio | Admin",
    "site_header": "JEAN DJANTA PortFolio | Admin",
    "site_brand" : "Jean DJ. | GATE",
    "welcome_sign": "ADMINISTRATION | JEAN DJ. ",
    "show_ui_builder": True,
    "copyright" : "Jean DJ. - All right Reserved 2025-2026",
    "site_logo": "img/logo.png",
    'login_logo' : None,
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

        {"name": "Site", "url": "/" }
    ],
    "language_chooser": True

    # "language_chooser" : True,
}
MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # for languages
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djFolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djFolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DB_TYP = os.getenv("DATABASE")
if DB_TYP == 'online' :
    DATABASES = {
        'default' : {
            'ENGINE' : 'django.db.backends.postgresql',
            'NAME' : os.getenv("DB_NAME"),
            'USER' : os.getenv("DB_USER"),
            'PASSWORD' : os.getenv("DB_PASSWORD"),
            'HOST' : os.getenv("DB_HOST"),
            'PORT' : os.getenv("DB_PORT", default="5432"),
            'OPTIONS': {
                'sslmode': 'require',
            },
            'CONN_MAX_AGE': 0
        }
    }
else :
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGES = [
    ('fr', _('Français')),
    ('en', _('Anglais'))
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# MEDIA_ROOT = BASE_DIR / 'media'

# supabase bucket
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AWS_ACCESS_KEY_ID = os.environ.get('SUPABASE_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('SUPABASE_SECRET_ACCESS_KEY')

AWS_STORAGE_BUCKET_NAME = os.getenv("SUPABASE_STORAGE_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = os.getenv("SUPABASE_S3_ENDPOINT_URL")
AWS_S3_ADDRESSING_STYLE = "path"
AWS_S3_REGION_NAME = os.getenv("SUPABASE_S3_REGION_NAME")

AWS_QUERYSTRING_AUTH = False
AWS_DEFAULT_ACL = 'public-read'

STORAGES = {
    "default": {
        "BACKEND": "djFolio.storages_backends.SupabaseMediaStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

from django.core.files.storage import storages

DEFAULT_STORAGE = storages.create_storage({
    "BACKEND": "storages.backends.s3boto3.S3Boto3Storage"
})

AWS_S3_ENDPOINT_URL_PUBLIC = os.getenv("SUPABASE_S3_ENDPOINT_URL_PUBLIC")

if DB_TYP == "online" :
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL_PUBLIC}/{AWS_STORAGE_BUCKET_NAME}/"
else:
    MEDIA_URL = 'media/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# print(f"\n \n ** debug : {DEBUG} \n Static : {STATIC_ROOT} \n url : {MEDIA_URL} ** \n \n")

INTERNAL_IPS = [
    '127.0.0.1',
]