# Generated by Django 6.0.1 on 2026-01-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='logo',
            field=models.ImageField(upload_to='folio/config'),
        ),
        migrations.AlterField(
            model_name='config',
            name='main_image',
            field=models.ImageField(upload_to='folio/config'),
        ),
    ]
