# Generated by Django 6.0.1 on 2026-01-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_alter_config_logo_alter_config_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='logo',
            field=models.ImageField(blank=True, upload_to='folio/config'),
        ),
        migrations.AlterField(
            model_name='config',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='folio/config'),
        ),
    ]
