# Generated by Django 6.0.1 on 2026-01-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0006_about_abouttranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField()),
                ('url', models.URLField()),
                ('ip', models.CharField()),
                ('when', models.DateTimeField()),
            ],
        ),
    ]
