# Generated by Django 6.0.1 on 2026-01-15 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0007_requestinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
