# Generated by Django 6.0.1 on 2026-01-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0008_requestinfo_created_requestinfo_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinfo',
            name='country',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='town',
            field=models.CharField(default=''),
        ),
    ]
