# Generated by Django 6.0.1 on 2026-01-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0009_requestinfo_country_requestinfo_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinfo',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestinfo',
            name='town',
            field=models.CharField(blank=True, null=True),
        ),
    ]
