# Generated by Django 6.0.1 on 2026-01-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0010_alter_requestinfo_country_alter_requestinfo_town'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestinfo',
            old_name='town',
            new_name='city',
        ),
    ]
