# Generated by Django 6.0.1 on 2026-01-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0013_remove_project_images_projectimage_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
