# Generated by Django 6.0.1 on 2026-01-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0014_project_top'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['visible', 'top'], name='folio_proje_visible_0787e1_idx'),
        ),
    ]
